Repository ElementsProject/lightning, pull requests merged in 2018-07, with the labels that each got.

#1647 travis: Add asciidoc, excluding latex, to the builder images
  contrib/Dockerfile.builder
  contrib/Dockerfile.builder.i386
Labels: docker, travis

#1648 pylightning: Subclass ValueError to access the returned error
  contrib/pylightning/lightning/__init__.py
  contrib/pylightning/lightning/lightning.py
  tests/test_lightningd.py
Labels: python

#1650 bitcoind: Smooth fee changes over a number of estimates
  lightningd/chaintopology.c
Labels: fee

#1558 Armbian build instructions
  doc/INSTALL.md
Labels: compilation, docs

#1658 jsonrpc: Remove `dev-blockheight` in favor of `getinfo`
  contrib/pylightning/lightning/lightning.py
  lightningd/chaintopology.c
Labels: json-rpc

#1678 gossip: Fix concurrent PR merge issue with structeq
  gossipd/gossip.c
Labels: bug, gossip

#1703 param: renamed files
  lightningd/Makefile
  lightningd/param.c
  lightningd/param.h
  lightningd/test/run-param.c
Labels: needinfo

#1765 pay: Exempt a fee from the maxfeepercent rule it is still tiny
  doc/lightning-pay.7
  doc/lightning-pay.7.txt
  lightningd/payalgo.c
  wallet/invoices.h
Labels: enhancement, fee, json-rpc
