Repository ElementsProject/lightning, pull requests merged in 2018-06, with the labels that each got.

#1570 daemon: print version in crash backtrace.
  common/daemon.c
Labels: crash, logging

#1551 Increase cltv_final
  lightningd/options.c
Labels: eclair-compat

#1583 gossip: Fix "already reaching" issue
  gossipd/gossip.c
Labels: bug, reconnect

#1546 Add 'make ncc' target, for source code analysis.
  Makefile
  doc/HACKING.md
Labels: compilation

#1613 Makefile: add bin-tarball rule to produce clightning-<version>-<distro>.tar.xz
  Makefile
Labels: compilation

#1616 docker: Add a usable dockerfile
  .gitattributes
  Dockerfile
  README.md
  tools/docker-entrypoint.sh
Labels: docker
