Repository ElementsProject/lightning, pull requests merged in 2018-08, with the labels that each got.

#1801 wallet: Add missing description field to the invoices iteration
  CHANGELOG.md
  wallet/invoices.c
Labels: json-rpc, wallet

#1817 travis: Actually build with clang if we want to
  .travis.yml
Labels: testing

#1857 docker: Make the bitcoind version configurable at build time
  Dockerfile
Labels: docker

#1855 contrib/short_channel_id-to-txid.sh: simple mapping util.
  contrib/short_channel_id-to-txid.sh
Labels: feature

#1861 Reconnect after feerate bad sig fix
  channeld/channel.c
  channeld/channel_wire.csv
  lightningd/peer_htlcs.c
  tests/test_connection.py
Labels: bug

#1893 lightningd: clean up tmpctx on exit before freeing ld.
  lightningd/lightningd.c
Labels: bug
