Repository ElementsProject/lightning, pull requests merged in 2018-03, with the labels that each got.

#1185 Add gitattribute to enforce lf on sh and py files
  .gitattributes
Labels: windows

#1251 chaintopology: set a fee floor to avoid creating unrelayable txs.
  lightningd/chaintopology.c
Labels: bitcoind, bug

#1261 pay: Also record how much we actually ended up sending.
  lightningd/json.c
  lightningd/pay.c
  wallet/db.c
  wallet/test/run-wallet.c
  wallet/wallet.c
  wallet/wallet.h
Labels: needs-rebase

#1292 travis: Updated docker builder images to include cppcheck
  contrib/Dockerfile.builder
  contrib/Dockerfile.builder.i386
Labels: docker
