Repository ElementsProject/lightning, pull requests merged in 2018-12, with the labels that each got.

#2141 plugin: Added .params.configuration to init call
  contrib/plugins/helloworld.py
  lightningd/lightningd.c
  lightningd/plugin.c
  lightningd/plugin.h
  lightningd/test/run-find_my_abspath.c
Labels: plugin

#2157 lightningd: only initialize plugins once we're ready for them to connect
  lightningd/lightningd.c
Labels: plugin

#2159 plugin: Fix an issue with string IDs ending up quoted twice
  lightningd/plugin.c
Labels: json-rpc, plugin

#2154 Make plugins more talkative (log notifications plugin->lightningd)
  contrib/plugins/helloworld.py
  lightningd/plugin.c
  tests/test_plugin.py
Labels: plugin

#2174 mocks: Drop invalid __sentinel__ value in generated mocks
  tools/mockup.sh
Labels: build

#2182 plugin: Add missing context to tal_fmt call on error message
  lightningd/plugin.c
Labels: crash

#2187 update pytest check when configure
  Makefile
  configure
Labels: build

#2172 Handle SIGTERM and SIGINT
  lightningd/lightningd.c
Labels: docker

#2205 pylightning: Increase buffer size for big JSON-RPC responses
  contrib/pylightning/lightning/lightning.py
Labels: pylightning, python
