Repository ElementsProject/lightning, pull requests merged in 2018-05, with the labels that each got.

#1462 doc: Remove libsodium-dev dependency, it's in-tree
  README.md
  contrib/Dockerfile.builder.fedora
  doc/INSTALL.md
Labels: docs

#1459 travis: Fix the locale in the builder images
  contrib/Dockerfile.builder
  contrib/Dockerfile.builder.i386
Labels: docker

#1473 pytest: Fix flaky `test_closing_id` test
  tests/test_closing.py
  tests/test_lightningd.py
Labels: testing

#1477 Fix BUILD_ASSERT failure in wireaddr_to_sockname
  common/wireaddr.c
  common/wireaddr.h
Labels: mac

#1484 Fix build on linux-musl
  ccan/README
  ccan/ccan/endian/endian.h
  ccan/ccan/opt/usage.c
  ccan/tools/configurator/configurator.c
Labels: pending-fix-confirmation

#1510 pytest: Do not set test-groups unless explicitly requested
  Makefile
Labels: testing
