Repository ElementsProject/lightning, pull requests merged in 2019-07, with the labels that each got.

#2795 onchaind: fix resolution detection of complex outputs, billboard
  onchaind/onchaind.c
Labels: bug, onchaind

#2806 plugins/pay: fix crash when we reach retry timeout.
  CHANGELOG.md
  plugins/pay.c
Labels: bug, crash

#2805 gossipd: fix inverted test in debug print.
  gossipd/routing.c
Labels: bug

#2834 travis: reduce parallelism for valgrind
  .travis/build.sh
Labels: travis

#2835 plugins: don't crash if getmanifest times out.
  lightningd/io_loop_with_timers.c
Labels: crash, plugin

#2857 gossipd: fix crash when we prune old, un-updated channel announcements.
  gossipd/routing.c
Labels: bug, crash, gossip

#2873 Fix update mocks
  Makefile
Labels: build

#2874 doc: fix typo in default port number.
  doc/lightning-connect.7
  doc/lightning-connect.7.txt
Labels: docs

#2875 Fix build fail on 32bit environment.
  common/sphinx.c
Labels: build
