Repository ElementsProject/lightning, pull requests merged in 2019-04, with the labels that each got.

#2513 gossip: Cache txout query failures
  gossipd/routing.c
  gossipd/routing.h
Labels: enhancement, gossip

#2405 fix: Add information about how many blocks to go until funding is confirmed
  CHANGELOG.md
  channeld/channel_wire.csv
  channeld/channeld.c
  channeld/full_channel.c
  channeld/full_channel.h
  channeld/test/run-full_channel.c
  common/initial_channel.c
  common/initial_channel.h
  lightningd/channel_control.c
  lightningd/channel_control.h
  lightningd/peer_control.c
  lightningd/test/run-invoice-select-inchan.c
  openingd/openingd.c
  wallet/test/run-wallet.c
Labels: needs-rebase

#2511 Subtype Parsing
  tools/generate-wire.py
Labels: v1.1

#2561 JSON: remove fields deprecated in 0.6.2.
  CHANGELOG.md
  lightningd/gossip_control.c
  lightningd/peer_control.c
Labels: json-rpc

#2566 Add a contrib script that makes it easier to test locally
  contrib/startup_regtest.sh
Labels: testing

#2580 channeld: give some tolerance for empty commitments.
  CHANGELOG.md
  channeld/channeld.c
Labels: lnd-compat

#2577 lightningd: don't abort if funding locks in during shutdown.
  lightningd/channel_control.c
Labels: bug, crash

#2586 wallet: fix crash when we have height requirement.
  CHANGELOG.md
  wallet/wallet.c
Labels: bug, crash, wallet

#2578 lightningd: make sure we correctly clear connections from connectd on error
  CHANGELOG.md
  lightningd/peer_control.c
Labels: bug, reconnect

#2593 Fix bockheight underflow if `minconf` > `blockheight`
  common/wallet_tx.h
  tests/test_misc.py
Labels: json-rpc, wallet
