Repository ElementsProject/lightning, pull requests merged in 2019-05, with the labels that each got.

#2609 gossipd: fix crash if we truncate store.
  gossipd/gossip_store.c
Labels: bug, crash

#2614 status: suppress status_trace/status_debug messages if queue too long.
  common/daemon_conn.c
  common/daemon_conn.h
  common/msg_queue.c
  common/msg_queue.h
  common/status.c
Labels: gossip, performance

#2613 pytest: Ensure lightningd instances have the correct numeric ids
  tests/utils.py
Labels: testing

#2626 bolt11: fix decoding and encoding of unknown fields.
  CHANGELOG.md
  common/bolt11.c
  common/test/run-bolt11.c
  tests/test_invoices.py
Labels: bug, invoice

#2627 Add 'delexpiredinvoice' to pylightning
  contrib/pylightning/lightning/lightning.py
Labels: pylightning

#2641 openingd: fix hangup when gossipd compacts.
  openingd/openingd.c
  tests/test_gossip.py
Labels: bug, gossip

#2646 Rpc: sort help output by command name
  lightningd/jsonrpc.c
Labels: Work in Progress

#2255 added manpage for listforwards command (needs change)
  doc/Makefile
  doc/lightning-listforwards.7
  doc/lightning-listforwards.7.txt
Labels: docs
