Repository ElementsProject/lightning, pull requests merged in 2019-09, with the labels that each got.

#3025 listfunds: add 'blockheight' for confirmed transactions
  CHANGELOG.md
  wallet/wallet.c
  wallet/walletrpc.c
Labels: json-rpc

#3024 Track withdrawal change
  tests/test_wallet.py
  wallet/wallet.c
Labels: bug

#3033 pytest: Collect errors in teardowns and allow running in ramdisk
  tests/fixtures.py
Labels: testing

#3034 docs: add install line
  doc/INSTALL.md
Labels: docs

#3028 Fix plugincmd memleak
  lightningd/plugin.c
Labels: testing

#3053 fix macOS build & update docs
  Makefile
  doc/INSTALL.md
Labels: build, mac

#3051 jsonrpc: add more fields to listfunds.
  CHANGELOG.md
  doc/lightning-listfunds.7
  doc/lightning-listfunds.7.md
  wallet/walletrpc.c
Labels: json-rpc, wallet

#3072 Fix cancel channel crash
  lightningd/channel_control.c
Labels: crash

#3081 gossipd: fix corner case where gossip msg too old after pending delay.
  gossipd/routing.c
Labels: crash, gossip

#3084 db: use correct backend for retrieving text fields.
  wallet/db.c
Labels: crash, db

#3104 Make option_static_remotekey non-EXPERIMENTAL now it's in spec.
  CHANGELOG.md
  Makefile
  channeld/channeld.c
  common/features.c
  common/features.h
  common/key_derive.c
  common/keyset.c
  hsmd/hsmd.c
  lightningd/channel_control.c
  lightningd/closing_control.c
  lightningd/opening_control.c
  onchaind/onchaind.c
  tests/test_connection.py
  tests/test_misc.py
  wire/extracted_peer_experimental_legacy
  wire/extracted_peer_wire_csv
Labels: protocol, spec
