Repository ElementsProject/lightning, pull requests merged in 2019-08, with the labels that each got.

#2893 channeld: delay sending channel_announcement by 60 seconds.
  channeld/channel_wire.csv
  channeld/channeld.c
  lightningd/channel_control.c
Labels: gossip

#2872 gossipd: don't use O_APPEND on the gossip_store.
  gossipd/gossip_store.c
Labels: cleanup, gossip

#2897 json-rpc: Add size and cumulative size to dev-memdump
  lightningd/memdump.c
Labels: json-rpc

#2871 pylightning: Warn users of plugins that may break due to extra args
  contrib/plugins/helloworld.py
  contrib/pylightning/lightning/plugin.py
  tests/plugins/dblog.py
  tests/plugins/fail_htlcs.py
  tests/plugins/hold_htlcs.py
  tests/plugins/hold_invoice.py
  tests/plugins/pretend_badlog.py
  tests/plugins/reject.py
  tests/plugins/reject_odd_funding_amounts.py
  tests/plugins/reject_some_invoices.py
  tests/plugins/shortcircuit.py
Labels: pylightning

#2902 log: make --log-file an early arg (since we move to dir early now).
  lightningd/log.c
Labels: bug, logging

#2901 wire: always ignore unknown odd messages.
  CHANGELOG.md
  common/read_peer_msg.c
  openingd/openingd.c
Labels: protocol, spec

#2915 lightningd: don't say 'killing channel' when HTLC times out.
  lightningd/peer_htlcs.c
  tests/test_misc.py
Labels: logging

#2920 cli: restore 0.7.0-style whitespace printing.
  cli/lightning-cli.c
  tests/test_misc.py
  tests/test_plugin.py
Labels: cli

#2919 gossipd: check that we don't try to access a deleted gossip entry.
  gossipd/gossip_store.c
Labels: gossip

#2931 lightningd: fix crash when peer disconnects after fundchannel_start, before cancel/complete
  lightningd/opening_control.c
Labels: bug, crash, funding

#2934 Fix `fundchannel` crash
  lightningd/peer_control.c
  lightningd/test/run-invoice-select-inchan.c
  tests/test_db.py
  wallet/test/run-wallet.c
  wallet/wallet.c
  wallet/wallet.h
Labels: bug

#2940 pytest: fix flaky "peer reconnected" message in test_option_upfront_s…
  tests/test_closing.py
Labels: testing

#2947 devtools: make clean should remove devtools/gen_print_onion_wire.[c,h,o]
  devtools/Makefile
Labels: build

#2948 cli: remove formatting hint correctly when it's not the last element.
  cli/lightning-cli.c
  cli/test/run-remove-hint.c
Labels: cli

#2957 v0.7.2-rc2
  CHANGELOG.md
Labels: release

#2962 Makefile: fix occasional race where we fail to compile tools/tests.
  Makefile
  tools/test/Makefile
Labels: build

#2965 v0.7.2
  CHANGELOG.md
Labels: release

#2971 v0.7.2.1: Nakamoto's Pre-approval by US Congress
  CHANGELOG.md
Labels: release

#2952 json: speed up shutdown.
  lightningd/subd.c
Labels: json-rpc, needs-rebase, performance

#2982 contrib: make stricter shellcheck from Ubuntu 18.04 happy
  contrib/bootstrap-node.sh
  contrib/startup_regtest.sh
Labels: build

#2984 doc: fix wording for fundchannel_complete
  doc/lightning-fundchannel_complete.7
  doc/lightning-fundchannel_complete.7.md
  doc/lightning-fundchannel_start.7
  doc/lightning-fundchannel_start.7.md
Labels: needs-rebase

#2985 The most important contrib/ addition, ever.
  contrib/plugins/cowsay.sh
Labels: MCP, Work in Progress, aarch64, addr, android, arm, backup, bitcoind, blocked, bsd, bug, build, channeld, cleanup, cli, closingd, compilation, config, cppcheck, crash, db, design, disconnect, distribution, dns, docker, docs, duplicate, eclair-compat, enhancement, explorer, feature, fee, forwarding, funding, good first issue, gossip, help wanted, hsmd, i386, invalid, invoice, json-rpc, lightningd, litecoin, lnd-compat, logging, logs, mac, needinfo, needs-rebase, onchaind, openingd, outdated, pay-plugin, pending-fix-confirmation, performance, plugin, protocol, pruning, pylightning, python, question, reconnect, regression, release, routing, spec, spruned, stale, testing, testnet, third-party, tor, travis, tx, update, v1.1, valgrind, voodoo, wallet, windows, wontfix
