Repository ElementsProject/lightning, pull requests merged in 2019-02, with the labels that each got.

#2285 make: Add an option to compile with address sanitizer
  Makefile
  configure
Labels: compilation

#2313 travis: Attempt to setup travis without docker and without sudo
  .travis.yml
  .travis/build.sh
  Makefile
Labels: travis

#2311 Fix docker image build from fresh clone
  Dockerfile
  contrib/linuxarm32v7.Dockerfile
Labels: docker

#2323 Update CCAN to pull in pipecmd fix
  ccan/README
  ccan/ccan/pipecmd/pipecmd.c
  ccan/tools/configurator/configurator.c
Labels: bug

#2327 pytest: Stabilize the test_pay_direct test
  tests/test_gossip.py
  tests/test_pay.py
  tests/utils.py
Labels: testing

#2358 fix crash with lightning charge and plugin opts
  lightningd/options.c
  lightningd/plugin.c
  lightningd/plugin.h
Labels: bug, json-rpc

#2356 pytest: Mark the worst gossip offenders as developer-only tests
  tests/test_connection.py
  tests/test_gossip.py
  tests/test_invoices.py
  tests/test_pay.py
Labels: testing, travis

#2332 doc: fix the command to cross-compile libgmp
  doc/INSTALL.md
Labels: arm, compilation

#2355 pylightning: Correctly return the remainder of a message back
  contrib/pylightning/lightning/lightning.py
Labels: pylightning, python

#2373 channeld: handle funding_locked message before reestablish.
  CHANGELOG.md
  channeld/channeld.c
Labels: lnd-compat

#2386 pylightning: Fix missing encode if first pass fails
  contrib/pylightning/lightning/lightning.py
Labels: bug, pylightning

#2397 build-release.sh: fix zipfile determinism.
  tools/build-release.sh
Labels: build, release
