Repository ElementsProject/lightning, pull requests merged in 2019-03, with the labels that each got.

#2329 doc/REPRODUCIBLE.md: how to make a reproducible zipfile and Ubuntu build.
  doc/REPRODUCIBLE.md
Labels: build, release

#2420 doc: fill in parameters in getroute manpage.
  doc/lightning-getroute.7
  doc/lightning-getroute.7.txt
Labels: docs

#2429 build: libsodium switched case in constants, add check for compat
  configure
Labels: build

#2480 pytest: fix flaky test_setchannel_fee_restart test.
  tests/test_pay.py
Labels: testing, travis
