Repository ElementsProject/lightning, pull requests merged in 2020-05, with the labels that each got.

#3721 pytest: extend timeout for test_payment_duplicate_uncommitted
  tests/test_pay.py
Labels: testing

#3737 hsmd: fix missing return bug
  hsmd/hsmd.c
Labels: bug

#3736 Makefile: don't print out what we're doing if --quiet/-s
  Makefile
Labels: build, cleanup
