Repository ElementsProject/lightning, pull requests merged in 2020-09, with the labels that each got.

#4016 Makefile: fix up sqlgen and docgen rules.
  doc/Makefile
  wallet/Makefile
  wallet/db_postgres_sqlgen.c
  wallet/db_sqlite3_sqlgen.c
  wallet/statements_gettextgen.po
Labels: cleanup

#4023 pytest: work around flaky test.
  tests/test_plugin.py
Labels: testing, travis

#4028 Makefile: fix typo which can cause build failures.
  connectd/test/Makefile
  external/Makefile
Labels: build

#4008 chore: .gitignore _exp_ wiregen
  wire/.gitignore
Labels: needs-rebase

#4035 pay: fix handling of legacy vs tlv encoding.
  plugins/keysend.c
  plugins/libplugin-pay.c
  plugins/libplugin-pay.h
  plugins/pay.c
Labels: bug, pay-plugin

#4036 Release 0.9.1 rc1
  CHANGELOG.md
Labels: release

#4034 Travis: spread from 10 to 11 valgrind runners
  .travis.yml
Labels: travis

#4042 CHANGELOG.md: 0.9.1rc2
  CHANGELOG.md
Labels: release

#4063 configure: refuse to compile without any database.
  configure
Labels: build

#4066 configure: clean up tmpfile if we fail.
  configure
Labels: build, cleanup

#4081 Makefile: work with shasum -a as well as sha256sum.
  Makefile
  configure
Labels: build, mac
