Repository ElementsProject/lightning, pull requests merged in 2020-08, with the labels that each got.

#3908 Routehints get ignored if invoice >10,000 sats
  plugins/pay.c
  tests/test_pay.py
Labels: bug

#3903 pyln.proto.message: don't let Message() init set implicit lengths.
  contrib/pyln-proto/pyln/proto/message/message.py
Labels: pyln

#3934 pytest: fix race in test_bcli.
  tests/test_plugin.py
Labels: testing

#3963 listpeers: add `features` array using BOLT9 names.
  doc/lightning-listpeers.7
  doc/lightning-listpeers.7.md
  lightningd/opening_control.c
  lightningd/peer_control.c
  tests/test_connection.py
Labels: json-rpc
