Repository ElementsProject/lightning, pull requests merged in 2020-01, with the labels that each got.

#3344 build: fix developer mode compilation on FreeBSD
  tools/mockup.sh
  tools/update-mocks.sh
Labels: bsd, build, compilation

#3386 wallet: remove edgecase around transaction checks
  lightningd/peer_control.c
  lightningd/watch.c
  wallet/wallet.c
  wallet/wallet.h
Labels: cleanup

#3435 sphinx: use struct secret for shared secret.
  channeld/channeld.c
  common/sphinx.c
  common/sphinx.h
  devtools/onion.c
  lightningd/peer_htlcs.c
  wallet/test/run-wallet.c
Labels: cleanup

#3423 pyln-proto: Added a couple of utilities to manage onions and zbase32
  contrib/pyln-proto/pyln/proto/onion.py
  contrib/pyln-proto/pyln/proto/primitives.py
  contrib/pyln-proto/pyln/proto/zbase32.py
  contrib/pyln-proto/requirements.txt
  contrib/pyln-proto/tests/test_onion.py
  contrib/pyln-proto/tests/test_primitives.py
Labels: pyln

#3448 lightningd: fix memleak false positive.
  lightningd/options.c
Labels: cleanup

#3460 lightningd: fix reorg bug where we don't fire watches.
  lightningd/chaintopology.c
  lightningd/chaintopology.h
Labels: bug
