Repository ElementsProject/lightning, pull requests merged in 2020-11, with the labels that each got.

#4178 bitcoin/signature: wrap libwally call.
  bitcoin/signature.c
Labels: crash

#4182 lightningd: fix crash if we abort after enabling notifications.
  lightningd/jsonrpc.c
  lightningd/lightningd.c
Labels: crash

#4065 `hsm_secret` generation from a seed-phrase
  doc/lightning-hsmtool.8
  doc/lightning-hsmtool.8.md
  tools/hsmtool.c
Labels: clightning_twit

#4179 pyln-testing: require bitcoin v0.20.1 for PSBT handling, and create wallet for v0.21
  contrib/pyln-testing/pyln/testing/fixtures.py
Labels: bitcoind

#4234 external/Makefile: fix parallel build with missing secp headers.
  external/Makefile
  tools/refresh-submodules.sh
Labels: build
