Repository ElementsProject/lightning, pull requests merged in 2020-04, with the labels that each got.

#3631 libplugin: fix compilation issue on recent gccs.
  plugins/libplugin.c
Labels: build

#3637 python: Consolidate requirements.txt files in a single place
  .travis/build.sh
  Makefile
  doc/HACKING.md
  doc/INSTALL.md
  doc/requirements.txt
  requirements.txt
  tests/requirements.txt
Labels: python

#3634 channeld: defer first update_fee until we have an HTLC to send.
  channeld/channeld.c
  tests/test_connection.py
  tests/test_pay.py
Labels: lnd-compat

#3646 lightningd: fix crash when failing htlc once channeld dies.
  lightningd/htlc_set.c
  lightningd/invoice.c
  lightningd/peer_htlcs.c
  lightningd/peer_htlcs.h
  lightningd/test/run-invoice-select-inchan.c
Labels: crash

#3648 pytest: fix flaky test_excluded_adjacent_routehint
  tests/test_pay.py
Labels: testing
