Repository ElementsProject/lightning, pull requests merged in 2021-05, with the labels that each got.

#4524 df-bugs: rm duplicate call to channeld
  lightningd/dual_open_control.c
Labels: bug

#4503 plugin notifications: minor cleanups.
  lightningd/plugin.c
  plugins/libplugin-pay.c
Labels: cleanup

#4541 pytest: fix flake in test_reconnect_no_update
  tests/test_connection.py
Labels: testing

#4550 Fix htlc error causing connclose
  lightningd/channel.c
  lightningd/channel.h
  lightningd/htlc_end.c
  lightningd/htlc_end.h
  lightningd/peer_htlcs.c
  tests/test_connection.py
  tests/test_misc.py
Labels: bug, disconnect

#4555 pay: fix corner case where we eliminate our own hint.
  plugins/libplugin-pay.c
  tests/test_pay.py
Labels: crash, pay-plugin
