Repository ElementsProject/lightning, pull requests merged in 2021-07, with the labels that each got.

#4658 improve hsm_secret doc
  doc/BACKUP.md
Labels: docs

#4657 added minimum word list needed
  tools/hsmtool.c
Labels: docs

#4641 docs: fix typo and wording
  doc/lightningd-config.5
  doc/lightningd-config.5.md
Labels: docs

#4662 Github actions: reduce lnprototest.
  .github/workflows/ci.yaml
Labels: testing

#4677 common: fix up missing file which can cause parallel build issues.
  common/Makefile
Labels: build

#4671 diff -R to diff -r
  doc/BACKUP.md
Labels: docs

#4681 connectd: allow out-of-bounds fees unless they're actually getting *worse*
  channeld/channeld.c
  tests/test_connection.py
Labels: fee, protocol
