Repository ElementsProject/lightning, pull requests merged in 2021-06, with the labels that each got.

#4583 pytest: speed up test_opening.py::test_funder_contribution_limits when !DEVELOPER
  contrib/pyln-testing/pyln/testing/utils.py
  tests/test_opening.py
Labels: testing

#4590 lightning/pay: don't crash when trying to send payment down unconfirmed channel
  lightningd/pay.c
Labels: crash

#4578 wire/Makefile: always generate non-exp files.
  wire/Makefile
  wire/bolt12_wiregen.c
  wire/bolt12_wiregen.h
  wire/common_wiregen.c
  wire/common_wiregen.h
  wire/onion_printgen.c
  wire/onion_printgen.h
  wire/onion_wiregen.c
  wire/onion_wiregen.h
  wire/peer_printgen.c
  wire/peer_printgen.h
  wire/peer_wiregen.c
  wire/peer_wiregen.h
  wire/test/Makefile
Labels: build

#4596 pytest: fix flake in test_misc.py::test_funding_reorg_*
  tests/test_misc.py
Labels: testing

#4602 plugins/bcli: fix uninitialized variable.
  plugins/bcli.c
Labels: bug, fee, plugin

#4606 invoice: allow creation of giant invoices.
  lightningd/invoice.c
  tests/test_invoices.py
Labels: invoice

#4622 fix docs
  doc/lightning-feerates.7
  doc/lightning-feerates.7.md
  doc/lightning-hsmtool.8
  doc/lightning-hsmtool.8.md
  doc/lightning-multiwithdraw.7
  doc/lightning-multiwithdraw.7.md
  doc/lightningd-config.5
  doc/lightningd-config.5.md
  doc/lightningd.8
  doc/lightningd.8.md
Labels: docs

#4621 lightningd: print out what errno we got if unexpected in sigchild.
  lightningd/lightningd.c
Labels: bug
