Repository ElementsProject/lightning, pull requests merged in 2022-08, with the labels that each got.

#5478 Thoroughly address multihtlc flakes
  tests/test_closing.py
Labels: flake

#5508 doc: note that setchannel maxhtlc/minhtlc only apply to *forwards*.
  doc/lightning-setchannel.7.md
Labels: docs

#5511 Fix derived_secret, use correct size of secretstuff.derived secret
  hsmd/libhsmd.c
  tests/test_misc.py
  tests/test_plugin.py
Labels: bug

#5534 doc: update usage of lightning-invoice.
  doc/lightning-invoice.7.md
Labels: docs

#5538 channeld: correct reversed shutdown message in billboard.
  common/billboard.c
Labels: bug

#5529 docs: use 'postgres' driver (not postgresql). Include plain url to guide
  doc/BACKUP.md
Labels: docs
