Repository ElementsProject/lightning, pull requests merged in 2023-07, with the labels that each got.

#6373 hsmtool: Add support for Signet network
  tools/hsmtool.c
Labels: bug fix

#6408 wallet: Fixes the compilation error due the db_binindings change
  wallet/db.c
Labels: build

#6412 Fix node announce self-advertize and advertize both sides of channels
  gossipd/gossipd.c
  tests/test_gossip.py
Labels: bug, gossip

#5996 Partial eq
  cln-rpc/src/primitives.rs
Labels: rust

#6425 channeld: don't close connection on invalid badonion code (LND bug?)
  channeld/channeld.c
Labels: lnd-compat

#6430 devtools/print_wire: long long instead of longing
  devtools/print_wire.c
Labels: compilation

#6432 lightningd: fix false memleak report (test flake)!
  lightningd/subd.c
Labels: flake

#6426 gossipd: don't "unmark" dying channels' updates if we receive them.
  gossipd/gossip_store.c
  gossipd/gossip_store.h
  gossipd/routing.c
  gossipd/test/run-check_channel_announcement.c
  gossipd/test/run-txout_failure.c
Labels: gossip, flake

#6439 docs: Incorrect params sequence for checkrune command
  doc/lightning-checkrune.7.md
  doc/schemas/checkrune.request.json
Labels: docs

#6435 bolt11: Don't push the size of the witness program for v1+ scripts
  common/bolt11.c
Labels: bug, invoice

#6443 gossipd: handle upgrade from version 11 gossip_store
  gossipd/gossip_store.c
Labels: gossip

#6453 SECURITY.md: fix email address
  SECURITY.md
Labels: docs

#6452 Update dead links in contributor workflow doc
  doc/contribute-to-core-lightning/contributor-workflow.md
Labels: docs

#6449 lightningd: don't crash if peer manages to spend onchain HTLC after we've abandoned upstream
  lightningd/htlc_end.c
  lightningd/peer_htlcs.c
Labels: crash, bug fix

#6454 gossipd: actually update own node announcement if needed
  gossipd/gossip_generation.c
Labels: gossip

#6455 devtools/credit: ! not ^ to invert the match set in sh.
  devtools/credit
Labels: bug, release

#6465 channeld: don't backtrace if master closes during sync read.
  channeld/channeld.c
Labels: logging
