Repository ElementsProject/lightning, pull requests merged in 2023-01, with the labels that each got.

#5837 connectd: don't ask DNS seeds for addresses on every reconnect.
  connectd/connectd.c
  connectd/connectd_wire.csv
  lightningd/connect_control.c
Labels: reconnect

#5871 cli: fix buffer overflow in (currently unused!) code for progress bars.
  cli/lightning-cli.c
Labels: bug, cli

#5817 common/test: fix typo in bolt12 test vector generation.
  common/test/run-bolt12_merkle.c
Labels: testing, spec

#5812 doc: fix accept-htlc-tlv-types description
  doc/lightning-listconfigs.7.md
  doc/schemas/listconfigs.schema.json
Labels: docs

#5897 gossip: Do not send warnings if we fail to parse a `channel_update`
  gossipd/routing.c
Labels: lnd-compat

#5880 comm: make sure that our version check is reliable
  common/test/Makefile
  common/test/run-version.c
  common/version.c
  common/version.h
  wallet/db.c
Labels: bug fix

#5934 common/bolt11: fix 32-bit compilation.
  common/bolt11.c
Labels: compilation
