Repository ElementsProject/lightning, pull requests merged in 2023-02, with the labels that each got.

#5938 plugins/pay: fix htlc_budget calc when we get temporary_channel_failure
  plugins/libplugin-pay.c
Labels: pay-plugin

#5931 Flag false-positive memleak in lightningd
  lightningd/lightningd.c
Labels: flake

#5946 lightningd: don't run more than one reconnect timer at once.
  lightningd/connect_control.c
  lightningd/lightningd.h
Labels: bug, reconnect

#5950 Fix offers with deprecated apis enabled
  plugins/offers_invreq_hook.c
  tests/test_pay.py
Labels: bug

#5939 lightningd: don't send channeld message to onchaind.
  lightningd/peer_htlcs.c
Labels: crash

#5961 pytest: fix flake in test_closing_disconnected_notify
  tests/test_closing.py
Labels: testing, flake

#5966 More accurate elements commitment tx size estimation
  common/initial_commit_tx.h
  tests/test_connection.py
  tests/test_gossip.py
  tests/utils.py
Labels: elements, bug fix

#5985 lightningd: don't put old deprecated `local_msat` and `remote_msat` in listpeerchannels.
  doc/lightning-listpeerchannels.7.md
  doc/schemas/listpeerchannels.schema.json
  lightningd/peer_control.c
Labels: json-rpc

#5992 fix: compilation error on armv7l 32 bit
  lightningd/dual_open_control.c
Labels: arm

#6005 [PATCH] fixes `FATAL SIGNAL 11` on loading gossmap
  common/gossmap.c
Labels: bug, crash, gossmap

#6042 autoclean: fix timer crash when we're cleaning two things at once.
  plugins/autoclean.c
  tests/test_plugin.py
Labels: bug, crash, plugin

#6043 pay: fix delpay to actually delete.
  lightningd/pay.c
  tests/test_pay.py
Labels: bug, plugin

#6032 [PATCH] do not send send peerstorage msg when disabled
  plugins/chanbackup.c
Labels: protocol, bug fix
