Repository ElementsProject/lightning, pull requests merged in 2023-08, with the labels that each got.

#6468 Make close return a signed tx, not an unsigned one, in JSON
  lightningd/closing_control.c
  lightningd/closing_control.h
  lightningd/peer_control.c
  lightningd/test/run-invoice-select-inchan.c
  tests/test_closing.py
  wallet/test/run-wallet.c
Labels: bug, json-rpc

#6472 CCAN: update for base64 compile fix on ARM.
  ccan/README
  ccan/ccan/base64/base64.c
Labels: aarch64

#6489 doc: give an example for multifundchannel
  doc/lightning-multifundchannel.7.md
Labels: docs

#6502 wallet: don't BROKEN log id payments.total_msat is null.
  wallet/wallet.c
Labels: bug, wallet

#6510 makefile: py plugins installed twice with `make install`
  Makefile
Labels: plugin, bug fix

#6514 build: more 32-bit printf fixes.
  channeld/channeld.c
  common/test/run-codex32.c
  plugins/renepay/test/run-payflow_map.c
Labels: build

#6487 docs: try to fix up readthedocs.io, so it has the latest man pages, but points to docs.corelighting.org for the rest
  doc/index.rst
Labels: docs

#6509 plugin/clnrest: Downgrading pyln-proto version from 23.08 to 23.5.2
  doc/index.rst
Labels: plugin, bug fix

#6518 contrib/pyln-grpc-proto: regenerate pyln/grpc/node_pb2.py
  .github/CODEOWNERS
Labels: grpc

#6517 channeld: don't send splice TLV fields unless negotiated.
  channeld/channeld.c
Labels: bug, eclair-compat

#6520 Disconnect on channeld death due to HTLC addition timeout
  lightningd/peer_htlcs.c
  tests/test_closing.py
Labels: bug, reconnect

#6525 listsendpays crash
  lightningd/invoice.c
  lightningd/pay.c
  plugins/renepay/pay.c
  tests/test_pay.py
Labels: crash, invoice

#6521 lightningd: use fsync not fdatasync.
  lightningd/configs.c
Labels: compilation, mac

#6346 Fix a typo in the description of field `private`
  doc/lightning-listclosedchannels.7.md
  doc/lightning-listpeerchannels.7.md
  doc/lightning-listpeers.7.md
  doc/schemas/listclosedchannels.schema.json
  doc/schemas/listpeerchannels.schema.json
  doc/schemas/listpeers.schema.json
Labels: docs

#6532 plugins: fix error report from bitcoin-cli exec failure.
  plugins/bcli.c
Labels: bug

#6543 gossipd: ignore redundant node_announcement in gossip_store.
  gossipd/gossip_store.c
Labels: component::gossipd

#6552 Release 23.08 rc2
  CHANGELOG.md
Labels: release

#6556 pay: still use channels for routehints even if peer says it's disabled.
  plugins/topology.c
Labels: lnd-compat, protocol

#6563 doc: Drive-by fixes of JSON examples in hooks.md
  doc/developers-guide/plugin-development/hooks.md
Labels: docs

#6566 nixos install: tweaks to get CLN building from fresh start
  doc/getting-started/getting-started/installation.md
Labels: docs

#6579 Fix routehint finding with minhtlc
  common/route.c
  doc/lightning-getroute.7.md
  plugins/libplugin-pay.c
  tests/test_pay.py
Labels: routing, pay-plugin

#6574 gossmap: fix false valgrind uninitialized error on arm64, ppc.
  common/gossmap.c
Labels: testing, arm, powerpc64le

#6587 CHANGELOG.md: Update for -rc3
  CHANGELOG.md
Labels: release

#6592 plugins/renepay: don't free waiting-for-addgossip flow!
  plugins/renepay/payment.c
Labels: crash

#6597 docker: bookworm image for arm32v7
  contrib/docker/Dockerfile.arm32v7
Labels: docker

#6595 Update backup-and-recover.md with the info about emergencyrecover and --recover.
  doc/beginners-guide/backup-and-recovery.md
Labels: docs

#6601 renepay: hack in workaround spendable reduction for release.
  plugins/renepay/uncertainty_network.c
Labels: bug

#6638 plugin/clnrest: do not read json payload if data length is zero
  plugins/clnrest/utilities/rpc_routes.py
  plugins/clnrest/utilities/shared.py
Labels: plugin
