Repository ElementsProject/lightning, pull requests merged in 2023-05, with the labels that each got.

#6242 pyln: remove unused variable
  contrib/pyln-testing/pyln/testing/utils.py
Labels: testing, pyln

#6245 jsonrpc: Remove the old "_msat" prefix in the listpeerchannels command
  lightningd/peer_control.c
Labels: bug fix

#6258 doc: remove duplicate wumbo key from listconfigs
  doc/lightning-listconfigs.7.md
Labels: docs

#6190 make: clean up lowdown install
  external/Makefile
Labels: build
