Repository ElementsProject/lightning, pull requests merged in 2023-03, with the labels that each got.

#6070 connectd: fix crash on freed context for new connections.
  connectd/connectd.c
Labels: crash

#6071 wallet: really allow broken migrations.
  wallet/db.c
Labels: bug, db

#6090 plugin: fetchinvoice: assign the quantity to the invrequest field
  plugins/fetchinvoice.c
  tests/test_pay.py
Labels: bug fix

#6107 channeld: don't spin trying to send commitment while waiting.
  channeld/channeld.c
Labels: logging, channeld

#6109 plugin: autoclean: cleanup the forwards with localfailed
  plugins/autoclean.c
Labels: bug fix
