Repository ElementsProject/lightning, pull requests merged in 2023-10, with the labels that each got.

#6769 lightnind: print the version of cln early
  lightningd/lightningd.c
  tests/test_misc.py
Labels: UX ✨

#6775 build: fix compilation issue on OpenBSD
  common/daemon.c
Labels: build

#6787 Closingd invalid fix
  lightningd/channel_control.c
Labels: testing, crash, continuous-integration

#6724 hsmd: name the hsmd_ready_channel to hsmd_setup_channel
  common/hsm_version.h
  hsmd/hsmd.c
  hsmd/hsmd_wire.csv
  hsmd/libhsmd.c
  openingd/dualopend.c
  openingd/openingd.c
Labels: hsmd

#6762 psbt: fix PSBT mutation in the changeset
  bitcoin/psbt.c
  bitcoin/psbt.h
  bitcoin/test/run-tx-bitcoin_tx_2of2_input_witness_weight.c
  common/psbt_open.c
  lightningd/dual_open_control.c
Labels: hsmd

#6812 lightningd: don't re-enter transaction if we have to call plugin_exclusive_loop
  lightningd/plugin.c
  lightningd/plugin_hook.c
Labels: crash, db

#6767 Restore any missing psbt metadata that resource constrained signers strip
  bitcoin/psbt.c
  bitcoin/psbt.h
  wallet/walletrpc.c
Labels: hsmd

#6734 CPFP for mutual close
  lightningd/peer_control.c
  lightningd/test/run-invoice-select-inchan.c
  tests/test_closing.py
  wallet/wallet.c
  wallet/wallet.h
Labels: wallet

#6815 splice: Update test for new logs
  tests/test_splicing.py
Labels: flake

#6823 splice: unwrap the old_secret during tx candidates
  channeld/channeld.c
Labels: hsmd
