Repository ElementsProject/lightning, pull requests merged in 2023-06, with the labels that each got.

#6312 fix: increase version cryptography python dep
  contrib/pyln-proto/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: dependencies

#6181 [RFC] lightningd: pass the current known block height down to the getchaininfo call
  doc/PLUGINS.md
  lightningd/bitcoind.c
  lightningd/bitcoind.h
  lightningd/chaintopology.c
  plugins/bcli.c
  tests/test_plugin.py
Labels: rfc

#6330 ci: re-enable the compilation workflow
  .github/workflows/ci.yaml
  .github/workflows/ci_build.yml
  .github/workflows/pre_build.yml
  .github/workflows/prototest.yaml
Labels: continuous-integration

#6335 fix: build on alpine linux
  common/configvar.c
Labels: build

#6356 More test flake fixes
  tests/test_misc.py
  tests/test_pay.py
Labels: testing

#6162 Added sample config and amended it to README
  README.md
  contrib/config-example
Labels: docs

#6350 pyln-proto: expose the tlv types
  contrib/pyln-proto/pyln/proto/message/__init__.py
Labels: bugfix-23.05.2

#6323 cln-grpc: Add some missing states to HtlcState
  cln-grpc/proto/primitives.proto
  contrib/pyln-testing/pyln/testing/primitives_pb2.py
Labels: bugfix-23.05.2

#6360 Correct INSTALL.md requirements for OpenBSD
  doc/INSTALL.md
Labels: build

#6230 add m1 native lib paths to Makefile
  Makefile
Labels: mac, build
