Repository ElementsProject/lightning, pull requests merged in 2023-04, with the labels that each got.

#6115 delpay: delete the payment by status from the db
  doc/lightning-delpay.7.md
  lightningd/pay.c
  tests/test_pay.py
  wallet/wallet.c
  wallet/wallet.h
Labels: bug fix

#6140 Fix scary INFO message on first connection to peer after startup
  lightningd/channel.c
  tests/test_connection.py
Labels: bug fix

#6121 test: add the timeout to the waitpay command
  tests/test_pay.py
Labels: testing

#6167 have towire_wally_psbt and fromwire_wally_psbt set safe psbt version
  bitcoin/psbt.c
Labels: hsmd
