Repository ElementsProject/lightning, pull requests merged in 2024-04, with the labels that each got.

#7192 lightningd: fix memleak where we didn't free plugin_hook_request when it was finished.
  lightningd/plugin_hook.c
Labels: bug

#7244 spelling: its `listinvoices` and `listinvoicerequests`
  contrib/msggen/msggen/schema.json
  doc/schemas/lightning-delinvoice.json
  doc/schemas/lightning-disableinvoicerequest.json
  doc/schemas/lightning-keysend.json
  doc/schemas/lightning-listsendpays.json
  doc/schemas/lightning-pay.json
  doc/schemas/lightning-sendpay.json
  doc/schemas/lightning-wait.json
  doc/schemas/lightning-waitanyinvoice.json
  doc/schemas/lightning-waitinvoice.json
  plugins/bkpr/bookkeeper.c
Labels: docs

#7232 msggen: add delpay method
  .msggen.json
  cln-grpc/proto/node.proto
  cln-grpc/src/convert.rs
  cln-grpc/src/server.rs
  cln-rpc/src/model.rs
  contrib/msggen/msggen/utils/utils.py
  contrib/pyln-grpc-proto/pyln/grpc/node_pb2.py
  contrib/pyln-grpc-proto/pyln/grpc/node_pb2_grpc.py
  contrib/pyln-testing/pyln/testing/grpc2py.py
Labels: needs-rebase

#7226 plugin/clnrest: Adding new config param as `clnrest-swagger-root`
  doc/developers-guide/app-development/rest.md
  doc/lightningd-config.5.md
  plugins/clnrest/clnrest.py
  plugins/clnrest/utilities/rpc_plugin.py
  plugins/clnrest/utilities/shared.py
Labels: plugin

#7233 msggen: add disableoffer method
  contrib/pyln-grpc-proto/pyln/grpc/node_pb2.py
  contrib/pyln-grpc-proto/pyln/grpc/primitives_pb2.py
Labels: needs-rebase
