Repository ElementsProject/lightning, pull requests merged in 2024-06, with the labels that each got.

#7411 doc: fix markdown in configuration node options
  doc/getting-started/getting-started/configuration.md
Labels: docs

#7335 script: Adding cl-repro script for easier builder image building
  contrib/cl-repro.sh
Labels: build

#7408 docker: Update github actions for Docker releases
  .github/workflows/docker-release.yml
Labels: docker

#7373 doc: fixed broken link to `setting-up-multiarchqemu-user-static`
  doc/contribute-to-core-lightning/release-checklist.md
Labels: docs

#7425 CI: set elements and bitcoind versions in one place.
  .github/scripts/install-bitcoind.sh
  .github/scripts/setup.sh
  .github/workflows/ci.yaml
Labels: continuous-integration

#7428 script: Adding Delete action for readme docs
  .github/scripts/sync-rpc-cmds.py
Labels: docs

#7396 docs: standardise notifications schema
  cln-grpc/proto/node.proto
  cln-grpc/src/convert.rs
  cln-rpc/src/notifications.rs
  contrib/msggen/msggen/schema.json
  contrib/msggen/msggen/utils/utils.py
  contrib/pyln-grpc-proto/pyln/grpc/node_pb2.py
  doc/rpc-schema-draft.json
  doc/schemas/notification/block_added.json
  doc/schemas/notification/block_added.request.json
  doc/schemas/notification/block_added.schema.json
  doc/schemas/notification/channel_open_failed.json
  doc/schemas/notification/channel_open_failed.request.json
  doc/schemas/notification/channel_open_failed.schema.json
  doc/schemas/notification/channel_opened.json
  doc/schemas/notification/channel_opened.request.json
  doc/schemas/notification/channel_opened.schema.json
  doc/schemas/notification/channel_state_changed.json
  doc/schemas/notification/channel_state_changed.request.json
  doc/schemas/notification/channel_state_changed.schema.json
  doc/schemas/notification/connect.json
  doc/schemas/notification/connect.request.json
  doc/schemas/notification/connect.schema.json
  doc/schemas/notification/custommsg.json
  doc/schemas/notification/custommsg.request.json
  doc/schemas/notification/custommsg.schema.json
Labels: docs

#7431 clnrest: Fixes `ssl_version` deprecated warning
  plugins/clnrest/clnrest.py
Labels: plugin::clnrest, component::cln-rest

#7432 doc: Updated warning box for wss-proxy
  doc/developers-guide/app-development/wss-proxy.md
Labels: docs, component::wss
