Repository ElementsProject/lightning, pull requests merged in 2024-08, with the labels that each got.

#7519 lightningd: don't create a second peer on stub recover if one already exists
  lightningd/opening_control.c
Labels: crash, plugin::recovery

#7524 offers: fix flake in fetchinvoice.
  plugins/fetchinvoice.c
Labels: flake

#7512 gossipd: always ask first peer for all the gossip.
  gossipd/seeker.c
  tests/test_gossip.py
Labels: gossip, component::gossipd, Highlight - Protocol

#7520 pyln-client: Deprecate category, desc and long description from method
  contrib/pyln-client/pyln/client/plugin.py
  doc/developers-guide/plugin-development/a-day-in-the-life-of-a-plugin.md
  doc/developers-guide/plugin-development/json-rpc-passthrough.md
Labels: pyln

#7525 offers: fix crash when receiving response to offer without `offer_issuser_id`
  plugins/fetchinvoice.c
Labels: crash, offers

#7558 askrene: reserve: fix assertion
  plugins/askrene/askrene.c
Labels: bug

#7564 openingd: don't ask for scid_alias in channel type if remote doesn't tell us they support it.
  openingd/openingd.c
Labels: lnd-compat, protocol

#7570 docker: Docker file fixes for reproducible builds
  contrib/docker/Dockerfile.builder.fedora
  contrib/reprobuild/Dockerfile.focal
  contrib/reprobuild/Dockerfile.jammy
  contrib/reprobuild/Dockerfile.noble
Labels: bug, continuous-integration

#7585 Adding PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#7603 docs: Added info for NFS version for db backup
  doc/beginners-guide/backup-and-recovery/advanced-db-backup.md
Labels: docs

#7620 Docker relative install cleanup
  Dockerfile
Labels: docker
