Repository ElementsProject/lightning, pull requests merged in 2024-09, with the labels that each got.

#7664 lightningd: make sure channels always have a local alias.
  lightningd/channel.c
  lightningd/opening_control.c
Labels: crash

#7661 subds: fix case where we keep retrying on EOF.
  wire/wire_io.c
Labels: bug

#7663 Fix listchannels includeprivate broken
  plugins/topology.c
  tests/test_plugin.py
Labels: bug, logging

#7598 Rust-bins: Upgrade tonic to v0.12 for v0.1.9
  Cargo.lock
  cln-grpc/Cargo.toml
  cln-rpc/Cargo.toml
  plugins/Cargo.toml
  plugins/grpc-plugin/Cargo.toml
Labels: cln-grpc, cln-rpc

#7644 hsmtool: provide nodeid from hsm secret.
  doc/lightning-hsmtool.8.md
  tests/test_wallet.py
  tools/hsmtool.c
Labels: hsmd, backup
