Repository ElementsProject/lightning, pull requests merged in 2024-07, with the labels that each got.

#7436 ci: Unify bitcoin versions for the whole project
  Dockerfile
  contrib/docker/Dockerfile.builder
  contrib/docker/Dockerfile.builder.fedora
  contrib/docker/Dockerfile.tester
  contrib/docker/scripts/setup.sh
Labels: continuous-integration

#7437 plugins: Remove requirements.txt from python plugins
  Dockerfile
  doc/developers-guide/app-development/rest.md
  doc/getting-started/getting-started/installation.md
  plugins/clnrest/requirements.txt
  plugins/wss-proxy/requirements.txt
Labels: component::cln-rest, component::wss

#7209 msggen: add `missing-grpc` command
  contrib/msggen/msggen/__main__.py
  contrib/msggen/msggen/utils/utils.py
Labels: cln-grpc, Highlight - UX and Dev Experience

#7433 bolt12: allow minimal offer
  cln-grpc/proto/node.proto
  cln-grpc/src/convert.rs
  cln-rpc/src/model.rs
  common/bolt12.c
  contrib/msggen/msggen/schema.json
  contrib/pyln-grpc-proto/pyln/grpc/node_pb2.py
  doc/schemas/lightning-offer.json
  lightningd/invoice.c
  plugins/offers.c
  plugins/offers_offer.c
  tests/test_pay.py
Labels: offers, component::bolt12-pay

#7449 doc: Tiny corrections in documentation
  contrib/msggen/msggen/schema.json
  doc/schemas/lightning-disconnect.json
  doc/schemas/lightning-plugin.json
Labels: docs
