Repository ElementsProject/lightning, pull requests merged in 2024-10, with the labels that each got.

#7700 docs: Updating release checklist with Hotfix release instructions
  doc/contribute-to-core-lightning/release-checklist.md
Labels: docs

#7659 ci: Prebuild action fails if Changelog is missing from all commits of…
  .github/workflows/ci.yaml
Labels: continuous-integration

#7705 pay-plugin: less listpeerchannels load
  plugins/libplugin-pay.c
Labels: needs-rebase

#7690 doc: update reference to the generator code
  doc/contribute-to-core-lightning/code-generation.md
Labels: docs
