Repository ElementsProject/lightning, pull requests merged in 2024-11, with the labels that each got.

#7780 github: Check if Changelog-None is in PR description
  .github/workflows/ci.yaml
Labels: continuous-integration

#7779 Remove swagger postman screenshots including .github folder
  plugins/clnrest/.github/screenshots/Postman-bkpr-plugin.png
  plugins/clnrest/.github/screenshots/Postman-with-body.png
  plugins/clnrest/.github/screenshots/Postman.png
  plugins/clnrest/.github/screenshots/Swagger-auth.png
  plugins/clnrest/.github/screenshots/Swagger-list-methods.png
  plugins/clnrest/.github/screenshots/Swagger-rpc-method.png
  plugins/clnrest/.github/screenshots/Swagger.png
Labels: docs, build

#7845 pytest: fix test_pay tests now we've deprecated experimental-offers.
  tests/autogenerate-rpc-examples.py
  tests/test_pay.py
Labels: bug

#7861 pyln-testing: disable seeker autoconnect by default
  contrib/pyln-testing/pyln/testing/utils.py
  tests/test_gossip.py
Labels: pyln-testing

#7873 connectd: force our own channel gossip to more peers
  connectd/multiplex.c
Labels: gossip

#7879 connectd: fix crash when we get an incoming conn while outgoing attempt is ratelimited
  connectd/connectd.c
Labels: crash

#7885 doc: Update info on 'cl-repro' script
  doc/contribute-to-core-lightning/release-checklist.md
  doc/getting-started/advanced-setup/repro.md
Labels: docs
