Repository ElementsProject/lightning, pull requests merged in 2025-02, with the labels that each got.

#8033 doc: Add new createrune example
  contrib/msggen/msggen/schema.json
  doc/schemas/lightning-commando-listrunes.json
  doc/schemas/lightning-commando-rune.json
  doc/schemas/lightning-createrune.json
  doc/schemas/lightning-showrunes.json
  tests/autogenerate-rpc-examples.py
  tools/fromschema.py
  tools/md2man.sh
Labels: docs

#8056 lightningd: don't kill onchaind if we are forcing a disconnect.
  lightningd/connect_control.c
Labels: onchaind, disconnect

#8074 common: fix memcpy error in Fischer-Yates shuffle.
  common/pseudorand.c
Labels: bug

#8077 lightning-cli: fix the access to man pages
  cli/lightning-cli.c
Labels: bug

#8103 docs: Lock example values to avoid unnecessary updates in schemas
  contrib/msggen/msggen/schema.json
  doc/schemas/lightning-bkpr-channelsapy.json
  doc/schemas/lightning-delforward.json
  doc/schemas/lightning-listforwards.json
  doc/schemas/lightning-listoffers.json
  doc/schemas/lightning-listpeerchannels.json
  doc/schemas/lightning-sql-template.json
  doc/schemas/lightning-xpay.json
  tests/autogenerate-rpc-examples.py
Labels: docs

#8109 doc: Add enableoffer in makefile
  contrib/msggen/msggen/schema.json
  doc/Makefile
  doc/index.rst
  doc/schemas/lightning-enableoffer.json
Labels: docs

#8111 Unilateral lease close fixes
  lightningd/onchain_control.c
  onchaind/onchaind.c
  onchaind/onchaind_wire.csv
  onchaind/test/run-grind_feerate.c
  tests/test_closing.py
Labels: bug, channel-lease
